name: "Docker AWS S3 Action"

description: "Simple s3 action"

runs:
  using: "docker"
  image: "ghcr.io/docker-collection/aws-cli-action:latest"

inputs:
  aws_s3_bucket:
    description: "Bucket name"
    required: true
  aws_access_key_id:
    description: "AWS access key id"
    required: true
  aws_secret_access_key:
    description: "AWS secret access key"
    required: true
  aws_region:
    description: "AWS region"
    required: false
  aws_s3_endpoint:
    description: "AWS endpoint"
    required: false
  aws_command:
    description: "AWS command"
    required: true
  dest_dir:
    description: "dest dir"
    required: false
  source_dir:
    description: "source dir"
    required: false
  aws_flags:
    description: "AWS flag"
    required: false
