name: "Testing"

on:
  push:
    branches:
      - "main"
  workflow_dispatch: {}

jobs:
  run_s3:
    runs-on: ubuntu-latest
    name: "Testing S3 Upload"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: aws s3
        uses: ./
        with:
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_s3_endpoint: ${{ secrets.AWS_S3_ENDPOINT }}
          aws_region: "us-west-1"
          source_dir: "temp"
          dest_dir: "./"
          aws_command: "sync"
