name: "Testing"

on: [push]

jobs:
  run_s3:
    runs-on: ubuntu-latest
    name: "Testing S3 Upload"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: aws s3
        uses: ./
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-1"
          SOURCE_DIR: "temp"
          AWS_COMMAN: "sync"
