name: "Single upload test"

on:
  workflow_call:
    secrets:
      aws_s3_bucket:
        required: true
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_s3_endpoint:
        required: true

jobs:
  s3_test:
    runs-on: ubuntu-latest
    name: "Test Single"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create testing folder & file
        run: |
          mkdir temp
          echo $(date) > temp/Test.txt

      - name: AWS S3 Uplaod Test
        uses: Docker-Collection/docker-aws-s3-action@main
        with:
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_s3_endpoint: ${{ secrets.AWS_S3_ENDPOINT }}
          source_dir: "temp"
          aws_command: "sync"

      - name: AWS S3 Download Test
        uses: Docker-Collection/docker-aws-s3-action@main
        with:
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_s3_endpoint: ${{ secrets.AWS_S3_ENDPOINT }}
          dest_dir: "Test.txt"
          aws_command: "cp"
      
      - name: Cat download file
        run: |
          cat Test.txt
          ls -alh

      - name: AWS S3 Remove Test
        uses: Docker-Collection/docker-aws-s3-action@main
        with:
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_s3_endpoint: ${{ secrets.AWS_S3_ENDPOINT }}
          dest_dir: "Test.txt"
          aws_command: "rm"
